### PR TITLE
feat: Add Binder support

### PR DESCRIPTION
**Pull request by matthewfeickert**
* Add binder directory to direct binder to the specific files.
* Symlink binder/requirements.txt to the top level to keep workflow the same for users.
* Add binder/runtime.txt to specify Python 3.10 runtime for better stability.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@sudo-panda this is ready for review. Nice [talk at PyHEP 2022](https://indico.cern.ch/event/1150631/timetable/#25-using-c-from-numba-fast-and) too! :)

**Comment by sudo-panda** [comment]
Hi @matthewfeickert! Thanks for the PR! 

Unfortunately it requires a specific branch of ROOT to be installed on the binder to work. Do you have any idea how to do that?

**Comment by matthewfeickert** [comment]
> Unfortunately it requires a specific branch of ROOT to be installed on the binder to work. Do you have any idea how to do that?

Ah indeed. I was just looking at that myself

https://github.com/sudo-panda/PyHEP-2022/blob/e6cab0e43bd1b5834944f091a7b24d54a0876522/README.md?plain=1#L18-L27

I think the answer is "yes, but it is way too much of a pain and unstable to be useful for the goals of preservation which motivated me opening this PR". :sweat_smile: So I'll close this out.

Thanks for all the nice work!

**Comment by sudo-panda** [comment]
No issues @matthewfeickert! Thanks again for the PR!

If you have any tutorial for installing external repos on binder please do share!

**Pull request closed without merging**
